### ISSUE TITLE
libva error: vaGetDriverNames() failed with unknown libva error

### ISSUE THREAD

**Issue by bruce-awareit** [elFarto/nvidia-vaapi-driver#245]
running "vainfo" command, it returns this error on archlinux.

linux kernel 6.5.3-arch1-1
nvidia-dkms 535.104.05-1
libva libva 2.19.0
libva-nvidia-driver 0.0.10-1

**Comment by detiam** [comment]
It's libva 2.20.0 update, just say vaGetDriverNames() failed to get driver name, if you set `LIBVA_DRIVER_NAME=nvidia` it will work still. I set this env var all the time, otherwise it won't work even in libva 2.19.
https://github.com/intel/libva/blob/8575b2bbc6d5cbf31690e682f4fa268d742fcb62/va/va.c#L683
Unknown why `vainfo` still says it's libva 2.19.0

**Comment by NuLL3rr0r** [comment]
@detiam thank you! You saved the day. I was having issues running CLion and your suggestion solved it.

**Comment by denji** [comment]
@detiam The internal libva code truncates the `nvidia` driver name string to `nvid`.

**Comment by elFarto** [comment]
I've updated the readme to better suggest that this setting is needed as the newer versions of libva have changed how driver detection works.

**Comment by mirh** [comment]
The error (and even the need to force drivers names) can be solved by compiling libva with the `-Dwith_legacy=nvctrl` meson build option. 
Otherwise there's nothing else instating the nvidia name to the roaster.

**Comment by duncanyoyo1** [comment]
I am getting this error again, not sure what caused it. Would be happy to diag.
