### ISSUE TITLE
Nvidia modeset warning everytime I open a video

### ISSUE THREAD

**Issue by NoXPhasma** [elFarto/nvidia-vaapi-driver#41]
Everytime I open a video in Firefox, I get this dmesg error message:
```
[drm:drm_new_set_master] *ERROR* [nvidia-drm] [GPU ID 0x00000a00] Failed to grab modeset ownership
```
An explanation why this message pops up: https://forums.developer.nvidia.com/t/ubuntu-21-10-failed-to-grab-modeset-ownership-with-495-44/193867/37

This has probably introduced with https://github.com/elFarto/nvidia-vaapi-driver/commit/34e7b7c170add540983e876b7979022e342c7f0a or  https://github.com/elFarto/nvidia-vaapi-driver/commit/b9c0d352260880677eb1b5b3198c058e9c8b97cc

**Comment by elFarto** [comment]
Thanks for reporting that, I hadn't noticed it on my machine. It's more a warning than an error in our case as we don't need to become a DRM master, just query some capabilities.

I've got a change queued up to use the render node if it exists, but we might not be able to retrieve that on the older 470 drivers. You can change `EGL_DRM_DEVICE_FILE_EXT` to `EGL_DRM_RENDER_NODE_FILE_EXT` if it's an urgent issue for you.

**Comment by NoXPhasma** [comment]
Changing the Extension in the file fixes the log spam :+1:

**Comment by guihkx** [comment]
Sorry to bump a closed issue, but having that message spammed in my journal every time I watch any video is a bit annoying, especially when seeing hundreds of them when I run `journalctl -p 3 -xb` to view actual  useful error messages that might have happened.

I think I understand it's a technical limitation of the R470 drivers not having `EGL_DRM_RENDER_NODE_FILE_EXT` support, but I was wondering if I could manually set the render node device using an environment variable, e.g. `NVD_RENDER_NODE`, and then your driver could try it first instead of querying  the master node.

Is this a reasonable request? 🤔

**Comment by elFarto** [comment]
It's a reasonable request. I think we can just guess at the render node, I believe it's just 128 + the card index. I'll double check that and add it in.

**Comment by elFarto** [comment]
I've committed a change that will either use the render node provided by the driver, or it will derive the render node from the master node and use that. This effectively stops it from ever using the master node, so should stop the error messages you're seeing.

**Comment by guihkx** [comment]
Just tested it, works great and no more complaints in the journal.

Thank you so very much!
